server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ride-service
          uri: lb://ride-service
          predicates:
            - Path=/api/rides/**
        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/api/drivers/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**

eureka:
  instance:
    status-page-url: http://localhost:${server.port}/webjars/swagger-ui/index.html
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
